"""
gen_sample_demo_package.py
==========================
Generates a real MTM sample package ZIP for the 2024 Caterpillar 299D3 XE and
writes it to static/demo_outputs/sample_mtm_package.zip.

Run from the project root:
    python scripts/gen_sample_demo_package.py

Does NOT touch production routes or modify any existing generation logic.
"""

import os
import sys
import shutil
import zipfile
import tempfile

# ── path setup ────────────────────────────────────────────────────────────────
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from dealer_input import DealerInput
from mtm_service import safe_lookup_machine, _run_spec_resolver
from listing_pack_builder import build_listing_pack_v1

# ── demo machine config ────────────────────────────────────────────────────────
DEALER_INPUT = DealerInput(
    year=2024,
    make="Caterpillar",
    model="299D3 XE",
    hours=320,
    cab_type="enclosed",
    ac=True,
    heater=True,
    high_flow="yes",
    two_speed_travel="yes",
    ride_control=True,
    backup_camera=True,
    air_ride_seat=True,
    asking_price=119500,
    condition_grade="Well Maintained",
    track_condition="95% remaining",
    condition_notes="Top-spec 299D3 XE. Single owner, dealer serviced throughout.",
)

DEALER_INFO = {
    "dealer_name": "Iron Valley Equipment",
    "phone": "(800) 555-0174",
    "accent_color": "yellow",
    "featured_template": "clean_marketplace",
}

SAMPLE_PHOTO = os.path.join(PROJECT_ROOT, "scripts", "_sample_machine.jpg")
OUTPUT_ZIP = os.path.join(PROJECT_ROOT, "static", "demo_outputs", "sample_mtm_package.zip")


def main():
    print("2024 Caterpillar 299D3 XE — MTM sample package generator")
    print("=" * 56)

    # ── 1. Registry lookup ────────────────────────────────────────────────────
    parsed = {"make": "Caterpillar", "model": "299D3 XE", "make_source": "explicit"}
    specs, confidence = safe_lookup_machine(parsed)
    if not specs:
        print("ERROR: Registry lookup failed for Caterpillar 299D3 XE")
        sys.exit(1)
    print(f"Registry match: {specs.get('equipment_type')} — confidence {confidence:.2f}")

    full_record = specs.get("full_record")

    # ── 2. Spec resolver ──────────────────────────────────────────────────────
    resolved_machine = _run_spec_resolver(
        "", parsed, specs, confidence, parsed_year=2024
    )
    resolved_specs = (resolved_machine or {}).get("resolved_specs") or {}
    print(f"Resolved specs: {len(resolved_specs)} fields")

    # ── 3. Build pack in temp session dir ────────────────────────────────────
    with tempfile.TemporaryDirectory(prefix="mtm_demo_") as session_dir:
        image_paths = [SAMPLE_PHOTO] if os.path.exists(SAMPLE_PHOTO) else []
        print(f"Photos: {len(image_paths)}")

        pack = build_listing_pack_v1(
            dealer_input=DEALER_INPUT,
            resolved_specs=resolved_specs,
            resolved_machine=resolved_machine,
            image_input_paths=image_paths,
            dealer_info=DEALER_INFO,
            session_dir=session_dir,
            session_web="",
            full_record=full_record,
        )

        if not pack.get("success"):
            print(f"ERROR: Pack generation failed: {pack}")
            sys.exit(1)

        src_zip = pack.get("zip_path")
        print(f"Source ZIP: {src_zip}")

        # ── 4. Repack with readme and target filenames ────────────────────────
        listing_dir = os.path.join(session_dir, "listing_output")
        _repack(listing_dir, src_zip, session_dir)


def _repack(listing_dir: str, src_zip: str, session_dir: str):
    """Repack the generated assets into the canonical demo ZIP with a readme."""

    readme_content = """\
MTM Sample Listing Package — Caterpillar 299D3 XE (2024)
=========================================================
Generated by Machine-to-Market (MTM) listing engine.

Files in this package
---------------------

listing_copy.txt
  Dealer-ready listing description generated by the MTM v3 copy engine.
  Category-aware, OEM-verified. Ready to paste into any listing platform.

spec_sheet.png
  Branded 1080x1350 spec sheet rendered by the MTM spec sheet renderer.
  Contains OEM-sourced performance specs, feature flags, and dealer info.

hero_card.png
  Branded 1080x1350 hero listing card rendered by the MTM card renderer.
  Clean Marketplace template — photo-dominant, minimal overlay.

image_pack_preview.png
  Sample branded listing photo processed through the MTM image pack pipeline.
  Resized, watermark-stamped, and formatted for multi-platform use.

readme.txt
  This file.

---
All assets are real MTM engine output — not static placeholders.
OEM specs sourced from Caterpillar Inc. official documentation.
"""

    # Collect generated files from the pack
    listing_photos_dir = os.path.join(listing_dir, "Listing_Photos")
    listing_txt = os.path.join(listing_dir, "listing_description.txt")

    spec_sheet_png  = _find_file(listing_photos_dir, "_02_spec_sheet.png")
    hero_card_png   = _find_file(listing_photos_dir, "_01_card.png")
    image_listing   = _find_file(listing_photos_dir, "_listing.")  # first numbered listing photo

    os.makedirs(os.path.dirname(OUTPUT_ZIP), exist_ok=True)

    with zipfile.ZipFile(OUTPUT_ZIP, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("readme.txt", readme_content)

        if os.path.exists(listing_txt):
            zf.write(listing_txt, "listing_copy.txt")
            print("  + listing_copy.txt  [REAL MTM OUTPUT]")
        else:
            print("  ! listing_copy.txt  MISSING")

        if spec_sheet_png and os.path.exists(spec_sheet_png):
            zf.write(spec_sheet_png, "spec_sheet.png")
            print("  + spec_sheet.png    [REAL MTM OUTPUT]")
        else:
            print("  ! spec_sheet.png    MISSING")

        if hero_card_png and os.path.exists(hero_card_png):
            zf.write(hero_card_png, "hero_card.png")
            print("  + hero_card.png     [REAL MTM OUTPUT]")
        else:
            print("  ! hero_card.png     MISSING")

        if image_listing and os.path.exists(image_listing):
            zf.write(image_listing, "image_pack_preview.png")
            print("  + image_pack_preview.png  [REAL MTM OUTPUT]")
        else:
            print("  ! image_pack_preview.png  MISSING (no photos or render failed)")

    size_kb = os.path.getsize(OUTPUT_ZIP) / 1024
    print(f"\nZIP written: {OUTPUT_ZIP}")
    print(f"Size: {size_kb:.1f} KB")


def _find_file(directory: str, suffix: str) -> str | None:
    """Return the first file in directory whose name contains suffix."""
    if not os.path.isdir(directory):
        return None
    for name in sorted(os.listdir(directory)):
        if suffix in name:
            return os.path.join(directory, name)
    return None


if __name__ == "__main__":
    main()
